version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot-arm-backend
    restart: unless-stopped
    ports:
      - "8080:8080"  # API and WebSocket port
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # For development, you can mount the entire codebase
      - .:/app
    environment:
      - SIMULATION_MODE=true
    networks:
      - robot-network
    # If you need to connect to Arduino, uncomment and adjust this
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0

  # Frontend React service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: robot-arm-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_PORT=8080  # Make sure frontend knows what port to use
    networks:
      - robot-network
    # For development, you can mount the source code
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Nginx reverse proxy (optional, uncomment for production)
  # This would allow you to access both frontend and backend on the same port
  # nginx:
  #   image: nginx:alpine
  #   container_name: robot-arm-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - robot-network

networks:
  robot-network:
    driver: bridge
